apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-volume
  labels:
    type: local
spec:
  storageClassName: jackett-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/coltean/Jackett"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-claim
spec:
  storageClassName: jackett-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels: 
    app: jackett
spec:
  selector:
    matchLabels:
      run: jackett
  replicas: 1
  template:
    metadata:
      labels:
        run: jackett
    spec:
      containers:
      - name: jackett
        image: coltean/jackett:jackett-colt
        ports:
        - containerPort: 9117
        volumeMounts:
        - name: jackett-data
          mountPath: '/config'
      imagePullSecrets:
      - name: regcred    
      volumes:
      - name: jackett-data
        persistentVolumeClaim:
          claimName: jackett-claim
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - default.svc.cluster.local  
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
---

apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    run: jackett
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9117
    nodePort: 9117
  selector:
    run: jackett
