apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    run: jackett
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9117
    nodePort: 9117
  selector:
    run: jackett
