apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-volume
  labels:
    type: local
spec:
  storageClassName: jackett-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/cristian/Jackett"