apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-claim
spec:
  storageClassName: jackett-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi