apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels: 
    app: jackett
spec:
  selector:
    matchLabels:
      run: jackett
  replicas: 1
  template:
    metadata:
      labels:
        run: jackett
    spec:
      containers:
      - name: jackett
        image: coltean/jackett:jackett-colt
        ports:
        - containerPort: 9117
        volumeMounts:
        - name: jackett-data
          mountPath: '/config'
      imagePullSecrets:
      - name: regcred    
      volumes:
      - name: jackett-data
        persistentVolumeClaim:
          claimName: jackett-claim